### ISSUE TITLE
构造方法

### ISSUE THREAD

**Issue by zzuhit** [arjinmc/ScaleProgressBar#1]
第二个构造方法：
public ScaleProgressBar(Context context, AttributeSet attrs){
        this(context, attrs, 0);
        initPaints();
    }
ps:这个算问题么？

**Comment by arjinmc** [comment]
什么问题？

**Comment by zzuhit** [comment]
this(context, attrs, 0);
是故意这么写的么？

**Comment by arjinmc** [comment]
确实有点笔误，原来封装的像放到同一个函数初始化画笔，后面又没改过来。你比较细心^.^
